version: "3.9"
services:
  backend:
    build: ./ChatApplication
    ports:
      - "3333:3333"
    depends_on:
      - database
  frontend:
    build: ./vue-project
    ports:
      - "5173:5173"
    depends_on:
      - backend
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: karthick@postgres
      POSTGRES_DB: ChatApp
    volumes :
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: